### PR TITLE
new kernel timers api

### PR DESCRIPTION
**Pull request by spotapov**

### CODE REVIEW

**Comment by a-zaki** [comment]
[Issue 1](https://trello.com/c/HvlmRGlD/1-issue-1)

**Comment by spotapov** [comment]
>  [Issue 1](https://trello.com/c/HvlmRGlD/1-issue-1)

Hello
This card doesn't exist in Trello or it is private

**Comment by a-zaki** [comment]
Sorry I was trying to choose between Trello and asana, ended with asana and deleted Trello account :)

Thanks for your PR, I will merge later today.

**Comment by spotapov** [comment]
Ok, thank you for this project

**Comment by a-zaki** [comment]
Build fails with 4.9.111, giving
`implicit declaration of function ‘timer_setup’`

It seems `timer_setup` was introduced in 4.14. Could you please put new changes between 

#if LINUX_VERSION_CODE <= KERNEL_VERSION(4,14,0)
...
#else
...
#endif

so that it does not break backward compatibility? My Ubuntu is still 4.4!

**Comment by spotapov** [comment]
I made and tested these changes on ubuntu 18.04 and kernel 4.15.
And i got the same error today on 4.9.0. I will add defines soon and test both cases

**Pull request merged**
